# fly.toml app configuration file generated for military-search-server on 2025-05-19T13:26:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'military-search-server'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop' # Consider 'off' or a longer timeout if startup is slow or requests are infrequent
  auto_start_machines = true
  min_machines_running = 0 # Consider 1 for faster responses if always active
  processes = ['app']

[[vm]]
  memory = '4gb'  # Increased from 1gb
  cpu_kind = 'shared'
  cpus = 2        # Increased from 1
  # memory_mb = 4096 # Fly.io infers this from 'memory', but explicit can be clearer
